name: game_trophy_manager
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.0

environment:
    sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    flare_flutter: ^3.0.1
    path_provider: ^2.0.2
    sqflite: ^2.0.0+3
    carousel_slider: ^4.0.0
    flutter_neumorphic:
        git:
            url: https://github.com/tsvillain/Flutter-Neumorphic.git
    flutter_keyboard_visibility: 5.0.3
    font_awesome_flutter: ^9.1.0
    material_design_icons_flutter: ^5.0.5955-rc.1
    line_awesome_flutter: ^1.1.0-nullsafety
    hidden_drawer_menu: ^3.0.0
    expansion_tile_card: ^2.0.0
    provider: ^5.0.0
    dio: ^4.0.0
    flutter_spinkit: ^5.0.0
    cached_network_image: ^3.1.0-alpha.1
    google_fonts: ^2.1.0
    flutter_widget_from_html: ^0.6.1
    another_flushbar: ^1.10.23
    flutter_svg: ^0.22.0
    share: ^2.0.4
    focused_menu: ^1.0.5
    infinite_scroll_pagination: ^3.1.0
    google_mobile_ads: ^0.13.6

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - images/
        - assets/anim.flr
        - assets/anim2.flr

    fonts:
        - family: Rammetto
          fonts:
              - asset: fonts/RammettoOne-Regular.ttf

    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
