allprojects {
    repositories {
        google()
        mavenCentral()
    }
    
    gradle.projectsEvaluated {
        tasks.withType(org.gradle.api.tasks.bundling.Jar) {
            duplicatesStrategy = 'include'
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    project.plugins.whenPluginAdded { plugin ->
        if (plugin.class.name == "com.android.build.gradle.LibraryPlugin") {
            project.android {
                if (namespace == null || namespace.isEmpty()) {
                    def manifestFile = file("${project.projectDir}/src/main/AndroidManifest.xml")
                    if (manifestFile.exists()) {
                        def manifest = new groovy.xml.XmlSlurper().parse(manifestFile)
                        namespace = manifest.@package.toString()
                    }
                }
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
